### ISSUE TITLE
Play Chatsounds if the source (player) is near the local player

### ISSUE THREAD

**Issue by be195** [Earu/neo-chatsounds#3]
Neo Chatsounds seemingly doesn't have a check if the player is nearby or not.
This results in creating a lot of WebAudio streams, which can possibly affect performance not in a good way:

![webaudio](https://wicopee.came-in-your.mom/K6MwMhcEzR.png)

## Suggestions
- Have a ConVar for distance
- Have the distance as a constant

**Comment by Earu** [comment]
https://github.com/Earu/neo-chatsounds/commit/f922d9adec6d5599625ae812cbb71d6169cf33b6 I'll be using PAS instead of a convar it makes more sense IMO
